List<String> patologiasMaisVistas = [
  "Selecione",
  "Exaustão física",
  "Desidratação",
  "Bolhas: Feridas nos pés",
  "Feridas ou infecções nos joelhos ",
  "Cortes ou lacerações graves ",
  "Traumas devido a quedas ou empurrões",
  "Problemas ortopédicos",
  "Dor nas pernas devido ao esforço prolongado",
  "Dor nos ombros devido à postura ou esforço",
  "Dor nas costas ",
  "Cãibras musculares",
  "Dor crônica ou inchaço nas articulações",
  "Problemas de circulação ",
  "Hipoglicemia Queda açúcar no sangue",
  "Pressão alta",
  "Pressão baixa",
  "Desmaios: Perda de consciência",
  "Bolhas severas ou rachaduras na pele dos pés",
  "Convulsões",
  "Ataques de pânico",
  "Problemas respiratórios",
  "Lesões por esforço repetitivo",
  "Reações alérgicas a picadas de insetos",
  "Queimaduras solares ou insolação",
  "Ferimentos leves",
  "Abuso de álcool ou drogas",
  "Acidentes vasculares cerebrais",
  "Outros"
];
